@host = localhost:7071
@dataset = 89bcda59-ef9a-4690-aaff-e0b91a82e758
@subject = 60059341-1517-4eae-af77-7b92ae51551c

#### Create a dataset

POST http://{{host}}/api/datasets/create
Content-Type: application/json

{
    "subjects": [
        {
            "url": "http://www.wikidata.org/entity/Q42",
            "metadata": {
                "Title": "Douglas Adams"
            }
        },
        {
            "url": "http://www.wikidata.org/entity/Q167605",
            "metadata": {
                "Title": "The Milkmaid (Vermeer)"
            }
        },
        {
            "url": "http://www.wikidata.org/entity/Q583",
            "metadata": {
                "Title": "Mont Blanc"
            }
        },
        {
            "url": "http://www.wikidata.org/entity/Q2752846",
            "metadata": {
                "Title": "Stichting CROW"
            }
        },
        {
            "url": "http://www.wikidata.org/entity/Q1438044",
            "metadata": {
                "Title": "Forschungsgesellschaft für Straßen- und Verkehrswesen"
            }
        }
    ]
}

#### Query for next Subject

GET http://{{host}}/api/datasets/{{dataset}}/next-subject

#### Query for next Subject, filtered

GET http://{{host}}/api/datasets/{{dataset}}/next-subject?filter=%7B%22and%22%3A%5B%7B%22not%22%3A%7B%22contains%22%3A%7B%22field%22%3A%22answers.q1%22%2C%22value%22%3A%22delete%22%7D%7D%7D%2C%7B%22not%22%3A%7B%22exists%22%3A%7B%22field%22%3A%22answers.q2%22%7D%7D%7D%2C%7B%22not%22%3A%7B%22exists%22%3A%7B%22field%22%3A%22answers.q3%22%7D%7D%7D%5D%7D

#### Fetch a dataset's statistics

GET http://{{host}}/api/datasets/{{dataset}}/stats?filter=%7B%22and%22%3A%5B%7B%22not%22%3A%7B%22contains%22%3A%7B%22field%22%3A%22answers.q1%22%2C%22value%22%3A%22delete%22%7D%7D%7D%2C%7B%22not%22%3A%7B%22exists%22%3A%7B%22field%22%3A%22answers.q2%22%7D%7D%7D%2C%7B%22not%22%3A%7B%22exists%22%3A%7B%22field%22%3A%22answers.q3%22%7D%7D%7D%5D%7D

#### Fetch a single subject

GET http://{{host}}/api/datasets/{{dataset}}/subjects/{{subject}}

#### Download a dataset

GET http://{{host}}/api/datasets/{{dataset}}/download
